FROM ubuntu:16.04
RUN apt-get -y update && \
    apt-get -y install python-pip git && \
    apt-get -y clean && \
    pip install -U pip && \
    pip install -U "ansible<2.5"
WORKDIR /bio-ansible
ADD . /bio-ansible/

RUN rm -f /bio-ansible/ansible.cfg

# TODO: bio-ansible should really do this itself
RUN mkdir -p /bioansible/software/modules
RUN mkdir -p /bioansible/software/source
RUN mkdir -p /bioansible/software/apps

# We add a pre-prepared host_vars/localhost that overrides some default
# variables for nicer paths inside the Docker container
ADD ./docker/host_vars/localhost /bio-ansible/host_vars/localhost

RUN ansible-playbook -c local -i hosts common.yml --tags apt && \
    ansible-playbook -c local -i hosts common.yml --tags pip && \
    ansible-playbook -c local -i hosts common.yml --skip-tags apt,pip && \
    ansible-playbook -c local -i hosts bio.yml --tags r_base,r_extras && \
    ansible-playbook -c local -i hosts bio.yml --tags blast && \
    ansible-playbook -c local -i hosts bio.yml --skip-tags r_base,r_extras,blast && \
    rm -rf /bio-ansbile && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
