FROM ubuntu:16.04

ARG TASK_TAGS=seqtk

RUN apt-get -y update && \
    apt-get -y install python-pip python3 && \
    apt-get -y clean && \
    pip install -U pip && \
    pip install -U ansible

WORKDIR /bio-ansible
ADD . /bio-ansible/

RUN rm /bio-ansible/ansible.cfg

# TODO: bio-ansible should really do this itself
RUN mkdir -p /bioansible/software/modules
RUN mkdir -p /bioansible/software/source
RUN mkdir -p /bioansible/software/apps

# We add a pre-prepared host_vars/localhost that overrides some default
# variables for nicer paths inside the Docker container
ADD ./docker/host_vars/localhost /bio-ansible/host_vars/localhost

RUN ansible-playbook -c local -i hosts bio.yml --tags $TASK_TAGS

RUN rm -rf /bio-ansbile && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
