FROM ubuntu:16.04
RUN apt-get -y update && \
    apt-get -y install python-pip python-virtualenv python3-pip python3-virtualenv \
                       git openjdk-8-jdk-headless ant golang-go unzip \
                       zlib1g-dev libncurses-dev libbz2-dev liblzma-dev \
                       tcl lua5.2 liblua5.2-dev lua-filesystem lua-posix && \
    apt-get -y clean && \
    pip install -U pip && \
    pip install -U ansible
# RUN git clone https://github.com/MonashBioinformaticsPlatform/bio-ansible.git
ADD . /bio-ansible/
WORKDIR /bio-ansible

RUN rm /bio-ansible/ansible.cfg

# We add a pre-prepared host_vars/localhost that overrides some default
# variables for nicer paths inside the Docker container
ADD ./docker/host_vars/localhost /bio-ansible/host_vars/localhost

# TODO: bio-ansible should really do this itself
RUN mkdir -p /bioansible/software/modules
RUN mkdir -p /bioansible/software/source
RUN mkdir -p /bioansible/software/apps

RUN ansible-playbook -c local -i hosts common.yml --tags lmod_etc,environment && \
    ansible-playbook -c local -i hosts bio.yml --tags lmod && \
    ansible-playbook -c local -i hosts bio.yml --tags bds && \
    ansible-playbook -c local -i hosts bio.yml --tags rnasik,star,subread,samtools,htslib,bedtools,picard,qualimap,fastqc,multiqc,bwa,hisat2 && \
    rm -rf /bio-ansible && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY docker/rnasik_wrapper.sh /bioansible/software/apps/rnasik.sh
RUN chmod +x /bioansible/software/apps/rnasik.sh
ENTRYPOINT ["/bioansible/software/apps/rnasik.sh"]
