#!/usr/bin/env python

import os,re,json

dirs = os.popen('find /usr/lib/jvm -mindepth 1 -maxdepth 1 -type d')

res = []
for l in dirs:
  l = l.rstrip('\n')
  n = os.path.basename(l)
  m = re.match( r'java-(\d-\w+).*', n)
  if m:
    ver = m.group(1)
    t = { 'base' : l,
          'dir' : n,
          'version' : ver,
          'help_text': 'Java JDK version : %s'%ver,
        }
    res.append(t)

print json.dumps(res)
